#ifndef RUCKIG_C_PRECISION_H
#define RUCKIG_C_PRECISION_H

#define RUCKIG_C_DBL_EPSILON 2.2204460492503131e-16
#define RUCKIG_C_TIME_EPS (2.0 * RUCKIG_C_DBL_EPSILON)

#define RUCKIG_C_PROFILE_V_EPS 1e-12
#define RUCKIG_C_PROFILE_A_EPS 1e-12
#define RUCKIG_C_PROFILE_J_EPS 1e-12
#define RUCKIG_C_PROFILE_P_PRECISION 1e-8
#define RUCKIG_C_PROFILE_V_PRECISION 1e-8
#define RUCKIG_C_PROFILE_A_PRECISION 1e-10
#define RUCKIG_C_PROFILE_FIRST_POSITION_PRECISION (4.0 * RUCKIG_C_DBL_EPSILON)
#define RUCKIG_C_PROFILE_POSITION_MATCH_PRECISION 1e-9
#define RUCKIG_C_PROFILE_T_MAX 1e12

#define RUCKIG_C_ROOTS_SHRINK_INTERVAL_TOLERANCE 1e-14

#define RUCKIG_C_BRAKE_TIME_EPS 2.2e-14

#define RUCKIG_C_WAYPOINT_POSITION_BOUND_EPS 1.0e-9

#define RUCKIG_C_BLOCK_DURATION_TIE_EPS_2 8.0
#define RUCKIG_C_BLOCK_DURATION_TIE_EPS_4_NEAR 32.0
#define RUCKIG_C_BLOCK_DURATION_TIE_EPS_4_FAR 256.0

#define RUCKIG_C_POLY_ROOT_REFINEMENT_TOLERANCE 1e-14
#define RUCKIG_C_POLY_BOUNDARY_EPS_FACTOR 8.0
#define RUCKIG_C_TIME_SYNC_RESIDUAL_TOLERANCE 1e-9
#define RUCKIG_C_JERK_LIMIT_TOLERANCE 1e-12

/* Preserve existing private macro names for implementation files that include internal.h. */
#define RUCKIG_DBL_EPSILON RUCKIG_C_DBL_EPSILON
#define RUCKIG_TIME_EPS RUCKIG_C_TIME_EPS

#endif
