if(NOT DEFINED RUCKIG_C_CURRENT_EXPORTS)
  message(FATAL_ERROR "RUCKIG_C_CURRENT_EXPORTS is required")
endif()
if(NOT DEFINED RUCKIG_C_BASELINE_SYMBOLS)
  message(FATAL_ERROR "RUCKIG_C_BASELINE_SYMBOLS is required")
endif()
if(NOT DEFINED RUCKIG_C_PUBLIC_SYMBOLS)
  message(FATAL_ERROR "RUCKIG_C_PUBLIC_SYMBOLS is required")
endif()
if(NOT DEFINED RUCKIG_C_PUBLIC_DIFF_OUTPUT)
  message(FATAL_ERROR "RUCKIG_C_PUBLIC_DIFF_OUTPUT is required")
endif()
if(NOT DEFINED RUCKIG_C_STRICT_PUBLIC_ABI)
  set(RUCKIG_C_STRICT_PUBLIC_ABI OFF)
endif()

foreach(input_file IN ITEMS
    "${RUCKIG_C_CURRENT_EXPORTS}"
    "${RUCKIG_C_BASELINE_SYMBOLS}"
    "${RUCKIG_C_PUBLIC_SYMBOLS}")
  if(NOT EXISTS "${input_file}")
    message(FATAL_ERROR "required ABI input does not exist: ${input_file}")
  endif()
endforeach()

function(ruckig_c_normalize_symbols input_file output_var)
  file(STRINGS "${input_file}" raw_lines)
  set(symbols "")
  foreach(line IN LISTS raw_lines)
    string(STRIP "${line}" stripped)
    if(stripped MATCHES "^#")
      continue()
    elseif(stripped MATCHES "^Name:[ \t]*(_?ruckig_[A-Za-z0-9_]+)(@@?[^ \t]+)?$")
      set(symbol "${CMAKE_MATCH_1}")
    elseif(stripped MATCHES "(^|[ \t])(_?ruckig_[A-Za-z0-9_]+)(@@?[^ \t]+)?$")
      set(symbol "${CMAKE_MATCH_2}")
    elseif(stripped MATCHES "^(_?ruckig_[A-Za-z0-9_]+)$")
      set(symbol "${CMAKE_MATCH_1}")
    else()
      continue()
    endif()
    if(symbol MATCHES "^_ruckig_")
      string(SUBSTRING "${symbol}" 1 -1 symbol)
    endif()
    list(APPEND symbols "${symbol}")
  endforeach()
  list(REMOVE_DUPLICATES symbols)
  list(SORT symbols)
  set(${output_var} "${symbols}" PARENT_SCOPE)
endfunction()

function(ruckig_c_list_difference lhs rhs output_var)
  set(result "${lhs}")
  foreach(item IN LISTS rhs)
    list(REMOVE_ITEM result "${item}")
  endforeach()
  set(${output_var} "${result}" PARENT_SCOPE)
endfunction()

function(ruckig_c_list_intersection lhs rhs output_var)
  set(result "")
  foreach(item IN LISTS lhs)
    if(item IN_LIST rhs)
      list(APPEND result "${item}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES result)
  list(SORT result)
  set(${output_var} "${result}" PARENT_SCOPE)
endfunction()

ruckig_c_normalize_symbols("${RUCKIG_C_CURRENT_EXPORTS}" current_symbols)
ruckig_c_normalize_symbols("${RUCKIG_C_BASELINE_SYMBOLS}" baseline_symbols)
ruckig_c_normalize_symbols("${RUCKIG_C_PUBLIC_SYMBOLS}" public_symbols)

ruckig_c_list_intersection("${current_symbols}" "${public_symbols}" current_public_symbols)
ruckig_c_list_intersection("${baseline_symbols}" "${public_symbols}" baseline_public_symbols)

ruckig_c_list_difference("${public_symbols}" "${current_symbols}" missing_public_symbols)
ruckig_c_list_difference("${current_public_symbols}" "${baseline_public_symbols}" added_public_symbols)
ruckig_c_list_difference("${baseline_public_symbols}" "${current_public_symbols}" removed_public_symbols)
ruckig_c_list_difference("${current_symbols}" "${public_symbols}" unapproved_exported_symbols)
ruckig_c_list_difference("${baseline_symbols}" "${public_symbols}" historical_baseline_internal_symbols)

list(LENGTH current_symbols current_count)
list(LENGTH baseline_symbols baseline_count)
list(LENGTH public_symbols public_count)
list(LENGTH current_public_symbols current_public_count)
list(LENGTH baseline_public_symbols baseline_public_count)
list(LENGTH missing_public_symbols missing_public_count)
list(LENGTH added_public_symbols added_public_count)
list(LENGTH removed_public_symbols removed_public_count)
list(LENGTH unapproved_exported_symbols unapproved_exported_count)
list(LENGTH historical_baseline_internal_symbols historical_baseline_internal_count)

if(missing_public_count GREATER 0
    OR added_public_count GREATER 0
    OR removed_public_count GREATER 0
    OR unapproved_exported_count GREATER 0)
  set(public_status "differences")
else()
  set(public_status "clean")
endif()

get_filename_component(diff_dir "${RUCKIG_C_PUBLIC_DIFF_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${diff_dir}")

set(report "Public exported-symbol comparison\n")
string(APPEND report "status: ${public_status}\n")
string(APPEND report "strict_public_abi: ${RUCKIG_C_STRICT_PUBLIC_ABI}\n")
string(APPEND report "current_snapshot: ${RUCKIG_C_CURRENT_EXPORTS}\n")
string(APPEND report "baseline_snapshot: ${RUCKIG_C_BASELINE_SYMBOLS}\n")
string(APPEND report "public_allowlist: ${RUCKIG_C_PUBLIC_SYMBOLS}\n")
string(APPEND report "current_symbol_count: ${current_count}\n")
string(APPEND report "baseline_symbol_count: ${baseline_count}\n")
string(APPEND report "approved_public_symbol_count: ${public_count}\n")
string(APPEND report "current_public_symbol_count: ${current_public_count}\n")
string(APPEND report "baseline_public_symbol_count: ${baseline_public_count}\n")
string(APPEND report "missing_public_symbol_count: ${missing_public_count}\n")
string(APPEND report "added_public_since_baseline_count: ${added_public_count}\n")
string(APPEND report "removed_public_since_baseline_count: ${removed_public_count}\n")
string(APPEND report "unapproved_exported_symbol_count: ${unapproved_exported_count}\n")
string(APPEND report "historical_baseline_internal_symbol_count: ${historical_baseline_internal_count}\n")

string(APPEND report "\nMissing public symbols from current exports:\n")
foreach(symbol IN LISTS missing_public_symbols)
  string(APPEND report "- ${symbol}\n")
endforeach()

string(APPEND report "\nAdded public symbols since baseline:\n")
foreach(symbol IN LISTS added_public_symbols)
  string(APPEND report "+ ${symbol}\n")
endforeach()

string(APPEND report "\nRemoved public symbols since baseline:\n")
foreach(symbol IN LISTS removed_public_symbols)
  string(APPEND report "- ${symbol}\n")
endforeach()

string(APPEND report "\nCurrent exported symbols not in the public allowlist:\n")
foreach(symbol IN LISTS unapproved_exported_symbols)
  string(APPEND report "! ${symbol}\n")
endforeach()

string(APPEND report "\nHistorical baseline symbols outside the public allowlist:\n")
foreach(symbol IN LISTS historical_baseline_internal_symbols)
  string(APPEND report "~ ${symbol}\n")
endforeach()

file(WRITE "${RUCKIG_C_PUBLIC_DIFF_OUTPUT}" "${report}")
message(STATUS "Wrote public exported-symbol comparison to ${RUCKIG_C_PUBLIC_DIFF_OUTPUT}")

if(NOT public_status STREQUAL "clean")
  if(RUCKIG_C_STRICT_PUBLIC_ABI)
    message(FATAL_ERROR "Public exported-symbol differences found; review ${RUCKIG_C_PUBLIC_DIFF_OUTPUT}")
  else()
    message(WARNING "Public exported-symbol differences found. Strict public ABI mode is OFF; review ${RUCKIG_C_PUBLIC_DIFF_OUTPUT}.")
  endif()
else()
  message(STATUS "Public exported symbols match the approved allowlist")
endif()
