if(NOT DEFINED RUCKIG_C_CURRENT_EXPORTS)
  message(FATAL_ERROR "RUCKIG_C_CURRENT_EXPORTS is required")
endif()
if(NOT DEFINED RUCKIG_C_BASELINE_SYMBOLS)
  message(FATAL_ERROR "RUCKIG_C_BASELINE_SYMBOLS is required")
endif()
if(NOT DEFINED RUCKIG_C_DIFF_OUTPUT)
  message(FATAL_ERROR "RUCKIG_C_DIFF_OUTPUT is required")
endif()

if(NOT EXISTS "${RUCKIG_C_CURRENT_EXPORTS}")
  message(FATAL_ERROR "current exported-symbol snapshot does not exist: ${RUCKIG_C_CURRENT_EXPORTS}")
endif()
if(NOT EXISTS "${RUCKIG_C_BASELINE_SYMBOLS}")
  message(FATAL_ERROR "baseline exported-symbol snapshot does not exist: ${RUCKIG_C_BASELINE_SYMBOLS}")
endif()

function(ruckig_c_normalize_exports input_file output_var)
  file(STRINGS "${input_file}" raw_lines)
  set(symbols "")
  foreach(line IN LISTS raw_lines)
    string(STRIP "${line}" stripped)
    if(stripped MATCHES "^Name:[ \t]*(_?ruckig_[A-Za-z0-9_]+)(@@?[^ \t]*)?$")
      set(symbol "${CMAKE_MATCH_1}")
    elseif(stripped MATCHES "(^|[ \t])(_?ruckig_[A-Za-z0-9_]+)(@@?[^ \t]*)?$")
      set(symbol "${CMAKE_MATCH_2}")
    elseif(stripped MATCHES "^(_?ruckig_[A-Za-z0-9_]+)$")
      set(symbol "${CMAKE_MATCH_1}")
    else()
      continue()
    endif()
    if(symbol MATCHES "^_ruckig_")
      string(SUBSTRING "${symbol}" 1 -1 symbol)
    endif()
    list(APPEND symbols "${symbol}")
  endforeach()
  list(REMOVE_DUPLICATES symbols)
  list(SORT symbols)
  set(${output_var} "${symbols}" PARENT_SCOPE)
endfunction()

ruckig_c_normalize_exports("${RUCKIG_C_CURRENT_EXPORTS}" current_symbols)
ruckig_c_normalize_exports("${RUCKIG_C_BASELINE_SYMBOLS}" baseline_symbols)

set(added_symbols "${current_symbols}")
foreach(symbol IN LISTS baseline_symbols)
  list(REMOVE_ITEM added_symbols "${symbol}")
endforeach()

set(removed_symbols "${baseline_symbols}")
foreach(symbol IN LISTS current_symbols)
  list(REMOVE_ITEM removed_symbols "${symbol}")
endforeach()

get_filename_component(diff_dir "${RUCKIG_C_DIFF_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${diff_dir}")

list(LENGTH current_symbols current_count)
list(LENGTH baseline_symbols baseline_count)
list(LENGTH added_symbols added_count)
list(LENGTH removed_symbols removed_count)

set(report "Exported-symbol baseline comparison\n")
string(APPEND report "current_snapshot: ${RUCKIG_C_CURRENT_EXPORTS}\n")
string(APPEND report "baseline_snapshot: ${RUCKIG_C_BASELINE_SYMBOLS}\n")
string(APPEND report "current_symbol_count: ${current_count}\n")
string(APPEND report "baseline_symbol_count: ${baseline_count}\n")
string(APPEND report "added_symbol_count: ${added_count}\n")
string(APPEND report "removed_symbol_count: ${removed_count}\n")
string(APPEND report "\nAdded symbols:\n")
foreach(symbol IN LISTS added_symbols)
  string(APPEND report "+ ${symbol}\n")
endforeach()
string(APPEND report "\nRemoved symbols:\n")
foreach(symbol IN LISTS removed_symbols)
  string(APPEND report "- ${symbol}\n")
endforeach()

file(WRITE "${RUCKIG_C_DIFF_OUTPUT}" "${report}")
message(STATUS "Wrote exported-symbol comparison to ${RUCKIG_C_DIFF_OUTPUT}")

if(added_count GREATER 0 OR removed_count GREATER 0)
  message(WARNING "Exported-symbol differences found. This is warning/evidence only for 0.2.x; review ${RUCKIG_C_DIFF_OUTPUT}.")
else()
  message(STATUS "Exported symbols match the baseline")
endif()
