if(NOT DEFINED RUCKIG_C_PUBLIC_HEADER)
  message(FATAL_ERROR "RUCKIG_C_PUBLIC_HEADER is required")
endif()
if(NOT DEFINED RUCKIG_C_OUTPUT_FILE)
  message(FATAL_ERROR "RUCKIG_C_OUTPUT_FILE is required")
endif()

if(NOT EXISTS "${RUCKIG_C_PUBLIC_HEADER}")
  message(FATAL_ERROR "public header does not exist: ${RUCKIG_C_PUBLIC_HEADER}")
endif()

function(ruckig_c_normalize_public_symbols input_file output_var)
  file(STRINGS "${input_file}" raw_lines)
  set(symbols "")
  foreach(line IN LISTS raw_lines)
    string(STRIP "${line}" stripped)
    if(stripped MATCHES "^#")
      continue()
    elseif(stripped MATCHES "^(ruckig_[A-Za-z0-9_]+)$")
      list(APPEND symbols "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES symbols)
  list(SORT symbols)
  set(${output_var} "${symbols}" PARENT_SCOPE)
endfunction()

file(STRINGS "${RUCKIG_C_PUBLIC_HEADER}" header_lines)
set(public_symbols "")
foreach(line IN LISTS header_lines)
  string(STRIP "${line}" stripped)
  if(stripped MATCHES "^RUCKIG_C_API[ \t]+.*(ruckig_[A-Za-z0-9_]+)[ \t]*\\(")
    list(APPEND public_symbols "${CMAKE_MATCH_1}")
  endif()
endforeach()
list(REMOVE_DUPLICATES public_symbols)
list(SORT public_symbols)

get_filename_component(output_dir "${RUCKIG_C_OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")

set(output "# Approved public C ABI symbols generated from include/ruckig_c/ruckig.h.\n")
set(output "${output}# Review before copying into docs/abi/public-symbols.txt.\n")
foreach(symbol IN LISTS public_symbols)
  string(APPEND output "${symbol}\n")
endforeach()
file(WRITE "${RUCKIG_C_OUTPUT_FILE}" "${output}")
message(STATUS "Wrote generated public symbol allowlist to ${RUCKIG_C_OUTPUT_FILE}")

if(DEFINED RUCKIG_C_EXPECTED_PUBLIC_SYMBOLS)
  if(NOT EXISTS "${RUCKIG_C_EXPECTED_PUBLIC_SYMBOLS}")
    message(FATAL_ERROR "expected public symbol allowlist does not exist: ${RUCKIG_C_EXPECTED_PUBLIC_SYMBOLS}")
  endif()

  ruckig_c_normalize_public_symbols("${RUCKIG_C_EXPECTED_PUBLIC_SYMBOLS}" expected_symbols)

  set(missing_symbols "${public_symbols}")
  foreach(symbol IN LISTS expected_symbols)
    list(REMOVE_ITEM missing_symbols "${symbol}")
  endforeach()

  set(extra_symbols "${expected_symbols}")
  foreach(symbol IN LISTS public_symbols)
    list(REMOVE_ITEM extra_symbols "${symbol}")
  endforeach()

  list(LENGTH public_symbols public_count)
  list(LENGTH expected_symbols expected_count)
  list(LENGTH missing_symbols missing_count)
  list(LENGTH extra_symbols extra_count)

  set(status "clean")
  if(missing_count GREATER 0 OR extra_count GREATER 0)
    set(status "differences")
  endif()

  if(DEFINED RUCKIG_C_VERIFY_OUTPUT)
    get_filename_component(verify_dir "${RUCKIG_C_VERIFY_OUTPUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${verify_dir}")
    set(report "Public symbol allowlist verification\n")
    string(APPEND report "status: ${status}\n")
    string(APPEND report "public_header: ${RUCKIG_C_PUBLIC_HEADER}\n")
    string(APPEND report "generated_allowlist: ${RUCKIG_C_OUTPUT_FILE}\n")
    string(APPEND report "expected_allowlist: ${RUCKIG_C_EXPECTED_PUBLIC_SYMBOLS}\n")
    string(APPEND report "header_public_symbol_count: ${public_count}\n")
    string(APPEND report "expected_public_symbol_count: ${expected_count}\n")
    string(APPEND report "missing_from_expected_count: ${missing_count}\n")
    string(APPEND report "extra_in_expected_count: ${extra_count}\n")
    string(APPEND report "\nSymbols present in header but missing from expected allowlist:\n")
    foreach(symbol IN LISTS missing_symbols)
      string(APPEND report "+ ${symbol}\n")
    endforeach()
    string(APPEND report "\nSymbols present in expected allowlist but absent from header:\n")
    foreach(symbol IN LISTS extra_symbols)
      string(APPEND report "- ${symbol}\n")
    endforeach()
    file(WRITE "${RUCKIG_C_VERIFY_OUTPUT}" "${report}")
    message(STATUS "Wrote public symbol allowlist verification to ${RUCKIG_C_VERIFY_OUTPUT}")
  endif()

  if(NOT status STREQUAL "clean")
    if(RUCKIG_C_FAIL_ON_MISMATCH)
      message(FATAL_ERROR "Public symbol allowlist is out of sync with ${RUCKIG_C_PUBLIC_HEADER}")
    else()
      message(WARNING "Public symbol allowlist is out of sync with ${RUCKIG_C_PUBLIC_HEADER}")
    endif()
  else()
    message(STATUS "Public symbol allowlist matches ${RUCKIG_C_PUBLIC_HEADER}")
  endif()
endif()
